config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users,
    controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }

  resources :queries
  resources :accounts
  resources :bancos
  resources :pagos
  resources :members
  resources :alejandros
  resources :predios
  resources :categories
  resources :products
  resources :shops

  root 'shops#index'
  
  get 'users/:id/shops' => 'users#shops', :as => :user_shops

  resources :users do
    member do
      get :shops
    end
  end
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :shops
  
  has_many :pagos
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @alejandros = Alejandro.all
    if params[:predio_id].blank?
      @shops = Shop.all
    else
      @shops = Shop.where(predio_id:params[:predio_id].titleize)
    end 
    @my_shops = Shop.select(:predio_id).order(:predio_id).distinct
  end
  
  before_filter :require_permission, only: :edit
  def require_permission
    if current_user.email != "ale@ale.cl"
      if (current_user.id != Shop.find(params[:id]).user_id)
        redirect_to root_path
        #Or do something else here
      end
    end
  end
  
  before_filter :require_permiso, only: :destroy
  def require_permiso
    if current_user.email == "ale@ale.cl"
      @shop.destroy
    elsif current_user.id != Shop.find(params[:id]).user_id
      redirect_to root_path
      #Or do something else here
    end
  end
  
  # GET /shops/1
  # GET /shops/1.json
  def show
    @q = Product.ransack(params[:q])
    @products = @q.result(distinct: true)
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    @predios = Predio.all
  end

  # GET /shops/1/edit
  def edit
    @categories = Category.all
    @predios = Predio.all
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)
    @shop.user_id = current_user.id if current_user
    @shop.predio_id = 1
    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Tienda creada exitosamente.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Tienda actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Tienda eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:image, :name, :greeting, :number, :whatsapp, :phone, :user_id, :predio_id, :category_id, :available)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    #  super(resource_name, resource)
    sign_in(resource)
    root_path
    #any_path # redirect_to is not necessary
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-109310748-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'UA-109310748-2');
  </script>

  <meta charset="utf-8">
  <title>PREDIOS APP</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootswatch/3.0.2/united/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 50px;
    }
    .button {
    background-color: #4CAF50; /* Green */
    border: none;
    color: white;
    padding: 16px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    -webkit-transition-duration: 0.4s; /* Safari */
    transition-duration: 0.4s;
    cursor: pointer;
    }
    .button3 {
    background-color: white; 
    color: black; 
    border: 2px solid #f44336;
    }
    .button3:hover {
    background-color: #f44336;
    color: white;
    }
    .button1 {
    background-color: white; 
    color: black; 
    border: 2px solid #4CAF50;
    }
    .button1:hover {
        background-color: #4CAF50;
        color: white;
    }
    h2.clase {  display:inline;}
    p.otra {display:inline;
    color: black;}
    a.link {color: blue; text-decoration: underline;}
  </style>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Predios App", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Tiendas", shops_path %></li>
        <li><%= link_to "Pagos", pagos_path %></li>
        <li><%= link_to "Consultas", queries_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Crear nuevo producto", new_product_path %></li>
        <% if current_user.email == "ale@ale.cl" %>
          <li><%= link_to "Predios", predios_path %></li>
          <li><%= link_to "Categories", categories_path %></li>
          <li><%= link_to "Alejandros", alejandros_path %></li>
          <li><%= link_to "Bancos", bancos_path %></li>
          <li><%= link_to "Tipos de cuenta", accounts_path %></li>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a><%= current_user.email %></a></li>
          <li><%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Iniciar sesión', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/shops/_stores.html.erb
<% @shops.each do |shop| %>
  <% @alejandros.each do |user| %>
    <% if shop.user.email == user.email %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <%= link_to image_tag(shop.image_url, class: "img-responsive aspect"), shop %><br>
          <div class="caption">
            <div class="bb">
              <% if shop.available %>
                <h2 class="clase"><span class="span"><%= shop.name %></span></h2><p class="otra">(abierta ahora)</p>
              <% else %>
                <h2 class="clase"><span class="span"><%= shop.name %></span></h2><p class="otra">(cerrada ahora)</p>
              <% end %>
            </div>
            <% if user_signed_in? %>
              <% if current_user.email == "ale@ale.cl" %>
                <h3><%= shop.user.email %></h3>
              <% end %>
            <% end %>
            <h4><%= shop.number %></h4>
            <% if shop.whatsapp %>
              <ul>
                <li>Tenemos Whatsapp</li>
              </ul>
            <% end %>
            <% if shop.phone %>
              <ul>
                <li>Puede llamarnos</li>
              </ul>
            <% end %>
            <p>
            <% if user_signed_in? %>
            <% if current_user.id == shop.user_id or current_user.email == "ale@ale.cl" %>
              <%= link_to 'Editar', edit_shop_path(shop), role: 'button', class: 'btn btn-success btn-sm' %>
              <%= link_to 'Eliminar', shop, method: :delete, data: { confirm: 'Are you sure?' }, role: 'button', class: 'btn btn-success btn-sm' %>
            <% end %>  
            <% end %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shops/index.html.erb
<meta name="apple-mobile-web-app-capable" content="yes"> 
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Montserrat:400,700" rel="stylesheet" type="text/css">
<!-- <p id="notice"><%#= notice %></p> -->
<%= form_for("", url: shops_path, method:'get', remote: true, html: { id: 'shops_index', role: 'form'} ) do |f| %> 
  <h1 align="center">Edificios con tiendas disponibles</h1>
    <div class="col-md-12 pure-css-select-style theme-default">
      <%= select_tag(:predio_id, options_for_select( @my_shops.collect {|p| [p.predio.name, p.predio_id] }), { prompt: 'Todas las Tiendas', class: ''})%> 
      <!-- <div class="pure-css-select-style theme-default">
        <select>
          <option value="volvo">Lorem ipsum dolor sit amet</option>
          <option value="saab">Consectetur adipisicing</option>
          <option value="mercedes">At molestiae blanditiis</option>
          <option value="audi">corrupti veritatis magni</option>
        </select>
      </div> -->
    </div>
  <!-- <ul class="nav nav-pills" role="tablist">
    <li><%#= link_to 'Todas las tiendas', shops_path, class: 'nav-item' %></li>
    <%# @my_shops.each do |s| %>
      <li><%#= link_to "#{s.predio.name}", controller: "shops", predio_id: "#{s.predio_id}" %></li>
    <%# end %>
  </ul> -->
  <br />
  <% if user_signed_in? %>
  <%= link_to "Mis Tiendas", user_shops_path(current_user), role: 'button', class: 'btn btn-success btn-xs' %>
  <% end %>
  <br />
    <div class="row">
      <br />
        <div id="stores">
          <%= render 'stores' %>
        </div>
      <br /><br /><br />
    </div>
<% end %>
<% if user_signed_in? %>  
<%= link_to 'Crear Nueva Tienda', new_shop_path, role: 'button', class: 'navbar-fixed-bottom button button3 btn-block' %>
<% end %>

<style type="text/css">

.pure-css-select-style {
  width: 100%;
  overflow: hidden;
}
.pure-css-select-style select {
  width: 100%;
  padding-right: 38px;
  border: none;
  box-shadow: none;
  background: transparent;
  background-image: none;
  -webkit-appearance: none;
  outline: none;
  cursor: pointer;

  /* Hide arrow on FF */
  -moz-appearance: none;
  text-indent: 0.01px;
  text-overflow: ellipsis;
}
/* Hide arrow on IE10*/
.pure-css-select-style select::-ms-expand {
  display: none;
}
.pure-css-select-style optgroup {
  color: inherit;
  font: inherit;
}
/* IE9: To hide select arrow we make the select overflow on the right side there is not another way :( */
@media screen and (min-width:0\0) {
  .pure-css-select-style select {
    width: calc( 100% + 58px );
  }
}

/* Themes default ----------------------------------------------------------- */
.theme-default {
  border: 1px solid #bbb;
  border-radius: 2px;
  /* <svg xmlns="http://www.w3.org/2000/svg" width="11" height="11" viewBox="0 0 11 11"><path d="M4.33 8.5L0 1L8.66 1z" fill="#666"/></svg> */
  background: #fff url('data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%2211%22%20height%3D%2211%22%20viewBox%3D%220%200%2011%2011%22%3E%3Cpath%20d%3D%22M4.33%208.5L0%201L8.66%201z%22%20fill%3D%22%23666%22%2F%3E%3C%2Fsvg%3E') right 10px center no-repeat;
}
.theme-default select {
  padding: 8px 38px 8px 8px;
  /* You can style text of the active select option */
  font: 400 18px/1.5 'Open Sans', sans-serif;
  color: #666;
}

.bootstrap-select:not([class*="col-"]):not([class*="form-control"]):not(.input-group-btn) {
  width: 100%;
}
</style>

<script type="text/javascript">
  $('.selectpicker').selectpicker({
      style: 'btn-default',
      size: 5,
  });
</script>

app/views/shops/index.js.erb
$('#stores').html('<%= escape_javascript(render("stores")) %>');